In [1]:
import numpy as np
import pandas as pd
import lightgbm as lgb
import joblib

from sklearn.metrics import (
    precision_recall_fscore_support,
    accuracy_score,
    balanced_accuracy_score,
    f1_score,
    confusion_matrix,
    roc_auc_score,
)
from sklearn.utils import shuffle

from imblearn.under_sampling import RandomUnderSampler
from imblearn.over_sampling import SMOTE

print("✅ All imports are working correctly!")


✅ All imports are working correctly!


In [1]:
import os
from pathlib import Path

import numpy as np
import pandas as pd
import lightgbm as lgb
import joblib

from sklearn.metrics import (
    precision_recall_fscore_support,
    accuracy_score,
    balanced_accuracy_score,
    f1_score,
    confusion_matrix,
)
from sklearn.utils import shuffle

from imblearn.under_sampling import RandomUnderSampler
from imblearn.over_sampling import SMOTE


# ============================================================
# 0) Paths and basic settings
# ============================================================

DATA_PATH = Path(r"C:\Users\LENOVO\Downloads\DF_ALL_4MOD_TRIMMED.csv")
MODELS_DIR = Path(r"C:\Users\LENOVO\Downloads\sp-data pre\LightGBM\output")

os.makedirs(MODELS_DIR, exist_ok=True)

SUBJECT_COL = "subject"
LABEL_COL   = "label"

RANDOM_STATE = 42
FOLD_SIZE_SUBJECTS = 5  # 5-subject grouped CV (نفس فكرة RF)

np.random.seed(RANDOM_STATE)


# ============================================================
# 1) Metadata columns (NOT used as features)
# ============================================================

meta_cols = [
    "subject",
    "run",
    "window_idx",
    "label",
    "run_base",
    "ecg_start_time_sec",
    "t_start",
    "t_end",
    "win_idx",
    "Unnamed: 0",
    "timestamp_center",
]


# ============================================================
# 2) Helper functions
# ============================================================

def hybrid_resample_l012(
    X,
    y,
    majority_class=0,
    mid_class=1,
    minority_class=2,
    max_majority_ratio=2.0,
    random_state=42,
):
    """
    Hybrid sampling strategy for labels {0, 1, 2} using:
      - Random UNDER-sampling for class 0 (majority)
      - SMOTE over-sampling for class 1 (preictal) and class 2 (seizure)
    """
    rng = np.random.RandomState(random_state)
    X = np.asarray(X)
    y = np.asarray(y)

    idx_maj = np.where(y == majority_class)[0]
    idx_mid = np.where(y == mid_class)[0]
    idx_min = np.where(y == minority_class)[0]

    n_maj = len(idx_maj)
    n_mid = len(idx_mid)
    n_min = len(idx_min)

    if n_mid == 0 or n_min == 0:
        raise ValueError("Classes 1 and 2 must be present for hybrid_resample_l012.")

    # 1) target counts
    mid_oversample_factor = 1.5
    target_mid = max(n_mid, int(n_mid * mid_oversample_factor))

    minority_target_ratio = 0.7
    raw_target_min = int(target_mid * minority_target_ratio)
    max_minority_factor = 10.0
    max_min = int(n_min * max_minority_factor)
    target_min = max(n_min, min(raw_target_min, max_min))

    target_maj = min(n_maj, int(max_majority_ratio * target_mid))

    sampling_strategy_under = {
        majority_class: target_maj,
        mid_class: n_mid,
        minority_class: n_min,
    }

    rus = RandomUnderSampler(
        sampling_strategy=sampling_strategy_under,
        random_state=random_state,
    )
    X_under, y_under = rus.fit_resample(X, y)

    n_mid_under = np.sum(y_under == mid_class)
    n_min_under = np.sum(y_under == minority_class)

    sampling_strategy_smote = {
        mid_class: max(n_mid_under, target_mid),
        minority_class: max(n_min_under, target_min),
    }

    try:
        smote = SMOTE(
            sampling_strategy=sampling_strategy_smote,
            random_state=random_state,
            k_neighbors=1,
        )
        X_bal, y_bal = smote.fit_resample(X_under, y_under)
    except ValueError:
        print("[WARN] SMOTE failed, falling back to simple oversampling.")

        X_bal = X_under
        y_bal = y_under

        idx_maj_u = np.where(y_under == majority_class)[0]
        idx_mid_u = np.where(y_under == mid_class)[0]
        idx_min_u = np.where(y_under == minority_class)[0]

        n_mid_u = len(idx_mid_u)
        n_min_u = len(idx_min_u)

        if n_mid_u < target_mid:
            extra_mid = target_mid - n_mid_u
            extra_idx_mid = rng.choice(idx_mid_u, size=extra_mid, replace=True)
            X_bal = np.concatenate([X_bal, X_under[extra_idx_mid]], axis=0)
            y_bal = np.concatenate([y_bal, y_under[extra_idx_mid]], axis=0)

        if n_min_u < target_min:
            extra_min = target_min - n_min_u
            extra_idx_min = rng.choice(idx_min_u, size=extra_min, replace=True)
            X_bal = np.concatenate([X_bal, X_under[extra_idx_min]], axis=0)
            y_bal = np.concatenate([y_bal, y_under[extra_idx_min]], axis=0)

    idx_all = np.arange(len(y_bal))
    idx_all = shuffle(idx_all, random_state=random_state)

    X_res = X_bal[idx_all]
    y_res = y_bal[idx_all]

    return X_res, y_res


def build_lgbm(params, num_classes):
    """
    Create a LightGBM classifier (multiclass, GPU).
    """
    return lgb.LGBMClassifier(
        objective="multiclass",
        num_class=num_classes,
        n_estimators=params["n_estimators"],
        max_depth=params["max_depth"],
        num_leaves=params["num_leaves"],
        learning_rate=params["learning_rate"],
        subsample=params["subsample"],
        colsample_bytree=params["colsample_bytree"],
        random_state=RANDOM_STATE,
        n_jobs=-1,
        verbose=-1,
        device_type="gpu",
        tree_learner="data",
        gpu_platform_id=0,
        gpu_device_id=0,
        max_bin=255,
    )


def lgbm_fit_predict(X_train, y_train, X_test, params, num_classes):
    model = build_lgbm(params, num_classes)
    print("Device type:", model.get_params()["device_type"])
    model.fit(X_train, y_train)
    y_test_pred = model.predict(X_test)
    return model, y_test_pred


def evaluate_metrics(y_true, y_pred, label_set=None):
    if label_set is None:
        label_set = np.unique(y_true)

    prec, rec, f1, support = precision_recall_fscore_support(
        y_true, y_pred, labels=label_set, zero_division=0
    )

    cm = confusion_matrix(y_true, y_pred, labels=label_set)
    total = cm.sum()

    tp = []
    fp = []
    fn = []
    tn = []

    for i in range(len(label_set)):
        TP = cm[i, i]
        FP = cm[:, i].sum() - TP
        FN = cm[i, :].sum() - TP
        TN = total - (TP + FP + FN)
        tp.append(TP)
        fp.append(FP)
        fn.append(FN)
        tn.append(TN)

    metrics = {
        "labels": label_set,
        "precision_per_class": prec,
        "recall_per_class": rec,
        "f1_per_class": f1,
        "support_per_class": support,
        "tp_per_class": np.array(tp),
        "fp_per_class": np.array(fp),
        "fn_per_class": np.array(fn),
        "tn_per_class": np.array(tn),
        "accuracy": accuracy_score(y_true, y_pred),
        "balanced_accuracy": balanced_accuracy_score(y_true, y_pred),
        "micro_f1": f1_score(y_true, y_pred, average="micro"),
        "macro_f1": f1_score(y_true, y_pred, average="macro"),
        "weighted_f1": f1_score(y_true, y_pred, average="weighted"),
        "confusion_matrix": cm,
    }

    return metrics


def print_metrics(metrics, header=""):
    labels  = metrics["labels"]
    prec    = metrics["precision_per_class"]
    rec     = metrics["recall_per_class"]
    f1      = metrics["f1_per_class"]
    support = metrics["support_per_class"]
    cm      = metrics["confusion_matrix"]

    if header:
        print("\n" + "=" * 70)
        print(header)
        print("=" * 70)

    print("\nPer-class metrics:")
    print("label\tprecision\trecall\t\tf1-score\tsupport")
    for i, c in enumerate(labels):
        print(f"{c}\t{prec[i]:.4f}\t\t{rec[i]:.4f}\t\t{f1[i]:.4f}\t\t{support[i]}")

    print("\nGlobal metrics:")
    print(f"Accuracy          : {metrics['accuracy']:.4f}")
    print(f"Balanced Accuracy : {metrics['balanced_accuracy']:.4f}")
    print(f"Micro-F1          : {metrics['micro_f1']:.4f}")
    print(f"Macro-F1          : {metrics['macro_f1']:.4f}")
    print(f"Weighted-F1       : {metrics['weighted_f1']:.4f}")

    print("\nConfusion matrix (rows = true, cols = predicted):")
    print(cm)

    total = cm.sum()
    print("\nPer-class confusion details (TP, FP, FN, TN):")
    for idx, c in enumerate(labels):
        TP = cm[idx, idx]
        FP = cm[:, idx].sum() - TP
        FN = cm[idx, :].sum() - TP
        TN = total - (TP + FP + FN)
        print(f"Label {c}: TP={TP}, FP={FP}, FN={FN}, TN={TN}")


# ============================================================
# 3) Load data
# ============================================================

print("Loading fused dataset...")
df = pd.read_csv(DATA_PATH)

if SUBJECT_COL not in df.columns or LABEL_COL not in df.columns:
    raise ValueError("Check SUBJECT_COL and LABEL_COL names. They are not found in the dataframe.")

print(f"Data shape: {df.shape}")
print("\nLabel distribution:")
print(df[LABEL_COL].value_counts())
print("\nLabel proportions (%):")
print(df[LABEL_COL].value_counts(normalize=True) * 100)

print("\nMetadata columns dropped from training:")
print(meta_cols)

feature_cols = [c for c in df.columns if c not in meta_cols]
print(f"\nNumber of feature columns used for training: {len(feature_cols)}")

X_all = df[feature_cols].astype("float32").values
y_all = df[LABEL_COL].values
subjects_all = df[SUBJECT_COL].values

label_set = np.unique(y_all)
print(f"Unique labels: {label_set}")


# ============================================================
# 4) FIXED hyperparameters for LightGBM (no nested tuning)
# ============================================================

FIXED_PARAMS = {
    "n_estimators": 400,
    "max_depth": 18,
    "num_leaves": 60,
    "learning_rate": 0.05,
    "subsample": 0.8,
    "colsample_bytree": 0.8,
}

print("\nUsing FIXED LightGBM hyperparameters:")
print(FIXED_PARAMS)


# ============================================================
# 5) 5-subject grouped CV (NO nested)
# ============================================================

unique_subjects = np.array(sorted(np.unique(subjects_all)))
outer_folds = [
    unique_subjects[i:i + FOLD_SIZE_SUBJECTS]
    for i in range(0, len(unique_subjects), FOLD_SIZE_SUBJECTS)
]

print(f"\nTotal subjects: {len(unique_subjects)}, "
      f"Number of folds (5-subject CV): {len(outer_folds)}")

all_test_y_true = []
all_test_y_pred = []
outer_macro_f1_list = []

for outer_idx, test_subj in enumerate(outer_folds, start=1):
    print("\n" + "#" * 80)
    print(f"OUTER Fold {outer_idx}/{len(outer_folds)} (5-subject grouped CV)")
    print("#" * 80)

    is_test = np.isin(subjects_all, test_subj)
    is_train = ~is_test

    X_train = X_all[is_train]
    y_train = y_all[is_train]
    X_test  = X_all[is_test]
    y_test  = y_all[is_test]

    print("Train subjects:", len(np.unique(subjects_all[is_train])))
    print("Test subjects :", len(np.unique(test_subj)))

    # Hybrid resampling على train فقط
    X_train_bal, y_train_bal = hybrid_resample_l012(
        X_train, y_train,
        majority_class=0,
        mid_class=1,
        minority_class=2,
        max_majority_ratio=2.0,
        random_state=RANDOM_STATE + outer_idx
    )

    model, y_pred = lgbm_fit_predict(
        X_train_bal, y_train_bal,
        X_test,
        FIXED_PARAMS,
        num_classes=len(label_set)
    )

    model_path = MODELS_DIR / f"lgbm_outer_{outer_idx:02d}_5subj.pkl"
    joblib.dump(model, model_path)
    print(f"Saved model: {model_path}")

    m = evaluate_metrics(y_test, y_pred, label_set)
    print_metrics(m, header=f"OUTER Fold {outer_idx} Test Metrics (LightGBM, GPU, 5-subject CV)")

    all_test_y_true.append(y_test)
    all_test_y_pred.append(y_pred)
    outer_macro_f1_list.append(m["macro_f1"])


# ============================================================
# 6) GLOBAL metrics
# ============================================================

all_test_y_true = np.concatenate(all_test_y_true)
all_test_y_pred = np.concatenate(all_test_y_pred)

global_m = evaluate_metrics(all_test_y_true, all_test_y_pred, label_set)
print_metrics(global_m, header="GLOBAL Metrics Across All 5-subject CV Folds (LightGBM, GPU)")


# ============================================================
# 7) FINAL deployment model (train on ALL subjects with FIXED_PARAMS)
# ============================================================

X_full_bal, y_full_bal = hybrid_resample_l012(
    X_all, y_all,
    majority_class=0,
    mid_class=1,
    minority_class=2,
    max_majority_ratio=2.0,
    random_state=RANDOM_STATE + 999
)

final_model = build_lgbm(FIXED_PARAMS, num_classes=len(label_set))
final_model.fit(X_full_bal, y_full_bal)

deployment_model_path = MODELS_DIR / "lgbm_final_deployment_5subj_gpu.pkl"
joblib.dump(final_model, deployment_model_path)

print("\nFinal LightGBM deployment model (GPU) trained on all subjects and saved to:")
print(deployment_model_path)
print("Use this model for real-time or external testing on new patients.")


Loading fused dataset...
Data shape: (1622677, 113)

Label distribution:
label
0    1312916
1     289844
2      19917
Name: count, dtype: int64

Label proportions (%):
label
0    80.910495
1    17.862088
2     1.227416
Name: proportion, dtype: float64

Metadata columns dropped from training:
['subject', 'run', 'window_idx', 'label', 'run_base', 'ecg_start_time_sec', 't_start', 't_end', 'win_idx', 'Unnamed: 0', 'timestamp_center']

Number of feature columns used for training: 103
Unique labels: [0 1 2]

Using FIXED LightGBM hyperparameters:
{'n_estimators': 400, 'max_depth': 18, 'num_leaves': 60, 'learning_rate': 0.05, 'subsample': 0.8, 'colsample_bytree': 0.8}

Total subjects: 113, Number of folds (5-subject CV): 23

################################################################################
OUTER Fold 1/23 (5-subject grouped CV)
################################################################################
Train subjects: 108
Test subjects : 5
[WARN] SMOTE failed, falling back 

c:\Users\LENOVO\Downloads\sp-data pre\xgb_gpu_env\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(


Saved model: C:\Users\LENOVO\Downloads\sp-data pre\LightGBM\output\lgbm_outer_01_5subj.pkl

OUTER Fold 1 Test Metrics (LightGBM, GPU, 5-subject CV)

Per-class metrics:
label	precision	recall		f1-score	support
0	0.8448		0.9769		0.9061		64940
1	0.3885		0.0370		0.0676		11160
2	0.2343		0.2245		0.2293		1332

Global metrics:
Accuracy          : 0.8285
Balanced Accuracy : 0.4128
Micro-F1          : 0.8285
Macro-F1          : 0.4010
Weighted-F1       : 0.7736

Confusion matrix (rows = true, cols = predicted):
[[63440   631   869]
 [10639   413   108]
 [ 1014    19   299]]

Per-class confusion details (TP, FP, FN, TN):
Label 0: TP=63440, FP=11653, FN=1500, TN=839
Label 1: TP=413, FP=650, FN=10747, TN=65622
Label 2: TP=299, FP=977, FN=1033, TN=75123

################################################################################
OUTER Fold 2/23 (5-subject grouped CV)
################################################################################
Train subjects: 108
Test subjects : 5
[WARN] SMO

c:\Users\LENOVO\Downloads\sp-data pre\xgb_gpu_env\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(


Saved model: C:\Users\LENOVO\Downloads\sp-data pre\LightGBM\output\lgbm_outer_02_5subj.pkl

OUTER Fold 2 Test Metrics (LightGBM, GPU, 5-subject CV)

Per-class metrics:
label	precision	recall		f1-score	support
0	0.8406		0.9455		0.8900		17789
1	0.0600		0.0127		0.0210		3150
2	0.1369		0.3491		0.1967		169

Global metrics:
Accuracy          : 0.8015
Balanced Accuracy : 0.4358
Micro-F1          : 0.8015
Macro-F1          : 0.3692
Weighted-F1       : 0.7547

Confusion matrix (rows = true, cols = predicted):
[[16820   627   342]
 [ 3080    40    30]
 [  110     0    59]]

Per-class confusion details (TP, FP, FN, TN):
Label 0: TP=16820, FP=3190, FN=969, TN=129
Label 1: TP=40, FP=627, FN=3110, TN=17331
Label 2: TP=59, FP=372, FN=110, TN=20567

################################################################################
OUTER Fold 3/23 (5-subject grouped CV)
################################################################################
Train subjects: 108
Test subjects : 5
[WARN] SMOTE faile

c:\Users\LENOVO\Downloads\sp-data pre\xgb_gpu_env\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(


Saved model: C:\Users\LENOVO\Downloads\sp-data pre\LightGBM\output\lgbm_outer_03_5subj.pkl

OUTER Fold 3 Test Metrics (LightGBM, GPU, 5-subject CV)

Per-class metrics:
label	precision	recall		f1-score	support
0	0.8696		0.9073		0.8880		59595
1	0.1748		0.0378		0.0622		8566
2	0.0582		0.4982		0.1043		546

Global metrics:
Accuracy          : 0.7956
Balanced Accuracy : 0.4811
Micro-F1          : 0.7956
Macro-F1          : 0.3515
Weighted-F1       : 0.7788

Confusion matrix (rows = true, cols = predicted):
[[54070  1530  3995]
 [ 7837   324   405]
 [  274     0   272]]

Per-class confusion details (TP, FP, FN, TN):
Label 0: TP=54070, FP=8111, FN=5525, TN=1001
Label 1: TP=324, FP=1530, FN=8242, TN=58611
Label 2: TP=272, FP=4400, FN=274, TN=63761

################################################################################
OUTER Fold 4/23 (5-subject grouped CV)
################################################################################
Train subjects: 108
Test subjects : 5
[WARN] SMOTE

c:\Users\LENOVO\Downloads\sp-data pre\xgb_gpu_env\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(


Saved model: C:\Users\LENOVO\Downloads\sp-data pre\LightGBM\output\lgbm_outer_04_5subj.pkl

OUTER Fold 4 Test Metrics (LightGBM, GPU, 5-subject CV)

Per-class metrics:
label	precision	recall		f1-score	support
0	0.8515		0.9738		0.9085		14104
1	0.6132		0.0863		0.1513		2700
2	0.3141		0.4914		0.3832		521

Global metrics:
Accuracy          : 0.8210
Balanced Accuracy : 0.5171
Micro-F1          : 0.8210
Macro-F1          : 0.4810
Weighted-F1       : 0.7747

Confusion matrix (rows = true, cols = predicted):
[[13734    52   318]
 [ 2226   233   241]
 [  170    95   256]]

Per-class confusion details (TP, FP, FN, TN):
Label 0: TP=13734, FP=2396, FN=370, TN=825
Label 1: TP=233, FP=147, FN=2467, TN=14478
Label 2: TP=256, FP=559, FN=265, TN=16245

################################################################################
OUTER Fold 5/23 (5-subject grouped CV)
################################################################################
Train subjects: 108
Test subjects : 5
[WARN] SMOTE fai

c:\Users\LENOVO\Downloads\sp-data pre\xgb_gpu_env\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(


Saved model: C:\Users\LENOVO\Downloads\sp-data pre\LightGBM\output\lgbm_outer_05_5subj.pkl

OUTER Fold 5 Test Metrics (LightGBM, GPU, 5-subject CV)

Per-class metrics:
label	precision	recall		f1-score	support
0	0.8616		0.8636		0.8626		50698
1	0.1889		0.0536		0.0835		7650
2	0.0488		0.4169		0.0873		710

Global metrics:
Accuracy          : 0.7533
Balanced Accuracy : 0.4447
Micro-F1          : 0.7533
Macro-F1          : 0.3445
Weighted-F1       : 0.7524

Confusion matrix (rows = true, cols = predicted):
[[43783  1759  5156]
 [ 6621   410   619]
 [  413     1   296]]

Per-class confusion details (TP, FP, FN, TN):
Label 0: TP=43783, FP=7034, FN=6915, TN=1326
Label 1: TP=410, FP=1760, FN=7240, TN=49648
Label 2: TP=296, FP=5775, FN=414, TN=52573

################################################################################
OUTER Fold 6/23 (5-subject grouped CV)
################################################################################
Train subjects: 108
Test subjects : 5
[WARN] SMOTE

c:\Users\LENOVO\Downloads\sp-data pre\xgb_gpu_env\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(


Saved model: C:\Users\LENOVO\Downloads\sp-data pre\LightGBM\output\lgbm_outer_06_5subj.pkl

OUTER Fold 6 Test Metrics (LightGBM, GPU, 5-subject CV)

Per-class metrics:
label	precision	recall		f1-score	support
0	0.8639		0.9657		0.9120		59673
1	0.0867		0.0113		0.0200		9000
2	0.1549		0.3420		0.2132		652

Global metrics:
Accuracy          : 0.8359
Balanced Accuracy : 0.4397
Micro-F1          : 0.8359
Macro-F1          : 0.3817
Weighted-F1       : 0.7896

Confusion matrix (rows = true, cols = predicted):
[[57627  1074   972]
 [ 8653   102   245]
 [  428     1   223]]

Per-class confusion details (TP, FP, FN, TN):
Label 0: TP=57627, FP=9081, FN=2046, TN=571
Label 1: TP=102, FP=1075, FN=8898, TN=59250
Label 2: TP=223, FP=1217, FN=429, TN=67456

################################################################################
OUTER Fold 7/23 (5-subject grouped CV)
################################################################################
Train subjects: 108
Test subjects : 5
[WARN] SMOTE 

c:\Users\LENOVO\Downloads\sp-data pre\xgb_gpu_env\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(


Saved model: C:\Users\LENOVO\Downloads\sp-data pre\LightGBM\output\lgbm_outer_07_5subj.pkl

OUTER Fold 7 Test Metrics (LightGBM, GPU, 5-subject CV)

Per-class metrics:
label	precision	recall		f1-score	support
0	0.7152		0.9676		0.8225		84385
1	0.3600		0.0163		0.0312		32864
2	0.0973		0.3354		0.1508		656

Global metrics:
Accuracy          : 0.6989
Balanced Accuracy : 0.4397
Micro-F1          : 0.6989
Macro-F1          : 0.3348
Weighted-F1       : 0.5982

Confusion matrix (rows = true, cols = predicted):
[[81648   951  1786]
 [32072   536   256]
 [  434     2   220]]

Per-class confusion details (TP, FP, FN, TN):
Label 0: TP=81648, FP=32506, FN=2737, TN=1014
Label 1: TP=536, FP=953, FN=32328, TN=84088
Label 2: TP=220, FP=2042, FN=436, TN=115207

################################################################################
OUTER Fold 8/23 (5-subject grouped CV)
################################################################################
Train subjects: 108
Test subjects : 5
[WARN] SM

c:\Users\LENOVO\Downloads\sp-data pre\xgb_gpu_env\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(


Saved model: C:\Users\LENOVO\Downloads\sp-data pre\LightGBM\output\lgbm_outer_08_5subj.pkl

OUTER Fold 8 Test Metrics (LightGBM, GPU, 5-subject CV)

Per-class metrics:
label	precision	recall		f1-score	support
0	0.7851		0.9565		0.8623		71070
1	0.2526		0.0039		0.0077		18993
2	0.0602		0.4195		0.1053		534

Global metrics:
Accuracy          : 0.7536
Balanced Accuracy : 0.4599
Micro-F1          : 0.7536
Macro-F1          : 0.3251
Weighted-F1       : 0.6787

Confusion matrix (rows = true, cols = predicted):
[[67975   219  2876]
 [18299    74   620]
 [  310     0   224]]

Per-class confusion details (TP, FP, FN, TN):
Label 0: TP=67975, FP=18609, FN=3095, TN=918
Label 1: TP=74, FP=219, FN=18919, TN=71385
Label 2: TP=224, FP=3496, FN=310, TN=86567

################################################################################
OUTER Fold 9/23 (5-subject grouped CV)
################################################################################
Train subjects: 108
Test subjects : 5
[WARN] SMOTE

c:\Users\LENOVO\Downloads\sp-data pre\xgb_gpu_env\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(


Saved model: C:\Users\LENOVO\Downloads\sp-data pre\LightGBM\output\lgbm_outer_09_5subj.pkl

OUTER Fold 9 Test Metrics (LightGBM, GPU, 5-subject CV)

Per-class metrics:
label	precision	recall		f1-score	support
0	0.8372		0.8692		0.8529		42237
1	0.1966		0.0473		0.0762		9879
2	0.0238		0.5034		0.0454		292

Global metrics:
Accuracy          : 0.7122
Balanced Accuracy : 0.4733
Micro-F1          : 0.7122
Macro-F1          : 0.3248
Weighted-F1       : 0.7020

Confusion matrix (rows = true, cols = predicted):
[[36712  1905  3620]
 [ 6997   467  2415]
 [  142     3   147]]

Per-class confusion details (TP, FP, FN, TN):
Label 0: TP=36712, FP=7139, FN=5525, TN=3032
Label 1: TP=467, FP=1908, FN=9412, TN=40621
Label 2: TP=147, FP=6035, FN=145, TN=46081

################################################################################
OUTER Fold 10/23 (5-subject grouped CV)
################################################################################
Train subjects: 108
Test subjects : 5
[WARN] SMOT

c:\Users\LENOVO\Downloads\sp-data pre\xgb_gpu_env\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(


Saved model: C:\Users\LENOVO\Downloads\sp-data pre\LightGBM\output\lgbm_outer_10_5subj.pkl

OUTER Fold 10 Test Metrics (LightGBM, GPU, 5-subject CV)

Per-class metrics:
label	precision	recall		f1-score	support
0	0.8296		0.9103		0.8681		89796
1	0.1153		0.0021		0.0041		17866
2	0.0367		0.4234		0.0675		836

Global metrics:
Accuracy          : 0.7570
Balanced Accuracy : 0.4453
Micro-F1          : 0.7570
Macro-F1          : 0.3132
Weighted-F1       : 0.7196

Confusion matrix (rows = true, cols = predicted):
[[81738   273  7785]
 [16317    37  1512]
 [  471    11   354]]

Per-class confusion details (TP, FP, FN, TN):
Label 0: TP=81738, FP=16788, FN=8058, TN=1914
Label 1: TP=37, FP=284, FN=17829, TN=90348
Label 2: TP=354, FP=9297, FN=482, TN=98365

################################################################################
OUTER Fold 11/23 (5-subject grouped CV)
################################################################################
Train subjects: 108
Test subjects : 5
[WARN] SM

c:\Users\LENOVO\Downloads\sp-data pre\xgb_gpu_env\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(


Saved model: C:\Users\LENOVO\Downloads\sp-data pre\LightGBM\output\lgbm_outer_11_5subj.pkl

OUTER Fold 11 Test Metrics (LightGBM, GPU, 5-subject CV)

Per-class metrics:
label	precision	recall		f1-score	support
0	0.8463		0.9699		0.9039		64721
1	0.0429		0.0061		0.0108		10742
2	0.2550		0.1898		0.2176		943

Global metrics:
Accuracy          : 0.8247
Balanced Accuracy : 0.3886
Micro-F1          : 0.8247
Macro-F1          : 0.3774
Weighted-F1       : 0.7699

Confusion matrix (rows = true, cols = predicted):
[[62770  1469   482]
 [10635    66    41]
 [  762     2   179]]

Per-class confusion details (TP, FP, FN, TN):
Label 0: TP=62770, FP=11397, FN=1951, TN=288
Label 1: TP=66, FP=1471, FN=10676, TN=64193
Label 2: TP=179, FP=523, FN=764, TN=74940

################################################################################
OUTER Fold 12/23 (5-subject grouped CV)
################################################################################
Train subjects: 108
Test subjects : 5
[WARN] SMO

c:\Users\LENOVO\Downloads\sp-data pre\xgb_gpu_env\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(


Saved model: C:\Users\LENOVO\Downloads\sp-data pre\LightGBM\output\lgbm_outer_12_5subj.pkl

OUTER Fold 12 Test Metrics (LightGBM, GPU, 5-subject CV)

Per-class metrics:
label	precision	recall		f1-score	support
0	0.8080		0.9741		0.8833		62512
1	0.0617		0.0014		0.0028		13997
2	0.0550		0.1119		0.0738		795

Global metrics:
Accuracy          : 0.7891
Balanced Accuracy : 0.3625
Micro-F1          : 0.7891
Macro-F1          : 0.3199
Weighted-F1       : 0.7155

Confusion matrix (rows = true, cols = predicted):
[[60890   297  1325]
 [13773    20   204]
 [  699     7    89]]

Per-class confusion details (TP, FP, FN, TN):
Label 0: TP=60890, FP=14472, FN=1622, TN=320
Label 1: TP=20, FP=304, FN=13977, TN=63003
Label 2: TP=89, FP=1529, FN=706, TN=74980

################################################################################
OUTER Fold 13/23 (5-subject grouped CV)
################################################################################
Train subjects: 108
Test subjects : 5
[WARN] SMOT

c:\Users\LENOVO\Downloads\sp-data pre\xgb_gpu_env\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(


Saved model: C:\Users\LENOVO\Downloads\sp-data pre\LightGBM\output\lgbm_outer_13_5subj.pkl

OUTER Fold 13 Test Metrics (LightGBM, GPU, 5-subject CV)

Per-class metrics:
label	precision	recall		f1-score	support
0	0.8479		0.9521		0.8970		34587
1	0.3554		0.0673		0.1132		6300
2	0.1179		0.3326		0.1741		469

Global metrics:
Accuracy          : 0.8103
Balanced Accuracy : 0.4507
Micro-F1          : 0.8103
Macro-F1          : 0.3948
Weighted-F1       : 0.7694

Confusion matrix (rows = true, cols = predicted):
[[32932   719   936]
 [ 5645   424   231]
 [  263    50   156]]

Per-class confusion details (TP, FP, FN, TN):
Label 0: TP=32932, FP=5908, FN=1655, TN=861
Label 1: TP=424, FP=769, FN=5876, TN=34287
Label 2: TP=156, FP=1167, FN=313, TN=39720

################################################################################
OUTER Fold 14/23 (5-subject grouped CV)
################################################################################
Train subjects: 108
Test subjects : 5
[WARN] SMOTE

c:\Users\LENOVO\Downloads\sp-data pre\xgb_gpu_env\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(


Saved model: C:\Users\LENOVO\Downloads\sp-data pre\LightGBM\output\lgbm_outer_14_5subj.pkl

OUTER Fold 14 Test Metrics (LightGBM, GPU, 5-subject CV)

Per-class metrics:
label	precision	recall		f1-score	support
0	0.8072		0.9133		0.8570		202966
1	0.1773		0.0491		0.0769		44806
2	0.1375		0.3108		0.1907		4540

Global metrics:
Accuracy          : 0.7490
Balanced Accuracy : 0.4244
Micro-F1          : 0.7490
Macro-F1          : 0.3748
Weighted-F1       : 0.7064

Confusion matrix (rows = true, cols = predicted):
[[185366  10157   7443]
 [ 41201   2199   1406]
 [  3080     49   1411]]

Per-class confusion details (TP, FP, FN, TN):
Label 0: TP=185366, FP=44281, FN=17600, TN=5065
Label 1: TP=2199, FP=10206, FN=42607, TN=197300
Label 2: TP=1411, FP=8849, FN=3129, TN=238923

################################################################################
OUTER Fold 15/23 (5-subject grouped CV)
################################################################################
Train subjects: 108
Test s

c:\Users\LENOVO\Downloads\sp-data pre\xgb_gpu_env\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(


Saved model: C:\Users\LENOVO\Downloads\sp-data pre\LightGBM\output\lgbm_outer_15_5subj.pkl

OUTER Fold 15 Test Metrics (LightGBM, GPU, 5-subject CV)

Per-class metrics:
label	precision	recall		f1-score	support
0	0.8338		0.9854		0.9033		68264
1	0.2150		0.0069		0.0134		12843
2	0.1488		0.1513		0.1500		899

Global metrics:
Accuracy          : 0.8230
Balanced Accuracy : 0.3812
Micro-F1          : 0.8230
Macro-F1          : 0.3556
Weighted-F1       : 0.7557

Confusion matrix (rows = true, cols = predicted):
[[67270   322   672]
 [12648    89   106]
 [  760     3   136]]

Per-class confusion details (TP, FP, FN, TN):
Label 0: TP=67270, FP=13408, FN=994, TN=334
Label 1: TP=89, FP=325, FN=12754, TN=68838
Label 2: TP=136, FP=778, FN=763, TN=80329

################################################################################
OUTER Fold 16/23 (5-subject grouped CV)
################################################################################
Train subjects: 108
Test subjects : 5
[WARN] SMOTE

c:\Users\LENOVO\Downloads\sp-data pre\xgb_gpu_env\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(


Saved model: C:\Users\LENOVO\Downloads\sp-data pre\LightGBM\output\lgbm_outer_16_5subj.pkl

OUTER Fold 16 Test Metrics (LightGBM, GPU, 5-subject CV)

Per-class metrics:
label	precision	recall		f1-score	support
0	0.7966		0.9037		0.8468		36585
1	0.1291		0.0523		0.0744		8357
2	0.2862		0.3043		0.2950		884

Global metrics:
Accuracy          : 0.7369
Balanced Accuracy : 0.4201
Micro-F1          : 0.7369
Macro-F1          : 0.4054
Weighted-F1       : 0.6953

Confusion matrix (rows = true, cols = predicted):
[[33061  2933   591]
 [ 7840   437    80]
 [  600    15   269]]

Per-class confusion details (TP, FP, FN, TN):
Label 0: TP=33061, FP=8440, FN=3524, TN=801
Label 1: TP=437, FP=2948, FN=7920, TN=34521
Label 2: TP=269, FP=671, FN=615, TN=44271

################################################################################
OUTER Fold 17/23 (5-subject grouped CV)
################################################################################
Train subjects: 108
Test subjects : 5
[WARN] SMOTE

c:\Users\LENOVO\Downloads\sp-data pre\xgb_gpu_env\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(


Saved model: C:\Users\LENOVO\Downloads\sp-data pre\LightGBM\output\lgbm_outer_17_5subj.pkl

OUTER Fold 17 Test Metrics (LightGBM, GPU, 5-subject CV)

Per-class metrics:
label	precision	recall		f1-score	support
0	0.6759		0.9612		0.7937		16243
1	0.4448		0.0526		0.0941		7200
2	0.4815		0.2052		0.2877		887

Global metrics:
Accuracy          : 0.6648
Balanced Accuracy : 0.4063
Micro-F1          : 0.6648
Macro-F1          : 0.3919
Weighted-F1       : 0.5682

Confusion matrix (rows = true, cols = predicted):
[[15613   473   157]
 [ 6782   379    39]
 [  705     0   182]]

Per-class confusion details (TP, FP, FN, TN):
Label 0: TP=15613, FP=7487, FN=630, TN=600
Label 1: TP=379, FP=473, FN=6821, TN=16657
Label 2: TP=182, FP=196, FN=705, TN=23247

################################################################################
OUTER Fold 18/23 (5-subject grouped CV)
################################################################################
Train subjects: 108
Test subjects : 5
[WARN] SMOTE f

c:\Users\LENOVO\Downloads\sp-data pre\xgb_gpu_env\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(


Saved model: C:\Users\LENOVO\Downloads\sp-data pre\LightGBM\output\lgbm_outer_18_5subj.pkl

OUTER Fold 18 Test Metrics (LightGBM, GPU, 5-subject CV)

Per-class metrics:
label	precision	recall		f1-score	support
0	0.8124		0.8924		0.8506		18064
1	0.1996		0.1239		0.1529		3890
2	0.4348		0.1505		0.2236		465

Global metrics:
Accuracy          : 0.7437
Balanced Accuracy : 0.3890
Micro-F1          : 0.7437
Macro-F1          : 0.4090
Weighted-F1       : 0.7165

Confusion matrix (rows = true, cols = predicted):
[[16121  1885    58]
 [ 3375   482    33]
 [  347    48    70]]

Per-class confusion details (TP, FP, FN, TN):
Label 0: TP=16121, FP=3722, FN=1943, TN=633
Label 1: TP=482, FP=1933, FN=3408, TN=16596
Label 2: TP=70, FP=91, FN=395, TN=21863

################################################################################
OUTER Fold 19/23 (5-subject grouped CV)
################################################################################
Train subjects: 108
Test subjects : 5
[WARN] SMOTE f

c:\Users\LENOVO\Downloads\sp-data pre\xgb_gpu_env\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(


Saved model: C:\Users\LENOVO\Downloads\sp-data pre\LightGBM\output\lgbm_outer_19_5subj.pkl

OUTER Fold 19 Test Metrics (LightGBM, GPU, 5-subject CV)

Per-class metrics:
label	precision	recall		f1-score	support
0	0.8510		0.9081		0.8787		73799
1	0.1728		0.0451		0.0715		12468
2	0.0217		0.2583		0.0400		391

Global metrics:
Accuracy          : 0.7810
Balanced Accuracy : 0.4038
Micro-F1          : 0.7810
Macro-F1          : 0.3301
Weighted-F1       : 0.7587

Confusion matrix (rows = true, cols = predicted):
[[67018  2689  4092]
 [11441   562   465]
 [  289     1   101]]

Per-class confusion details (TP, FP, FN, TN):
Label 0: TP=67018, FP=11730, FN=6781, TN=1129
Label 1: TP=562, FP=2690, FN=11906, TN=71500
Label 2: TP=101, FP=4557, FN=290, TN=81710

################################################################################
OUTER Fold 20/23 (5-subject grouped CV)
################################################################################
Train subjects: 108
Test subjects : 5
[WARN] 

c:\Users\LENOVO\Downloads\sp-data pre\xgb_gpu_env\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(


Saved model: C:\Users\LENOVO\Downloads\sp-data pre\LightGBM\output\lgbm_outer_20_5subj.pkl

OUTER Fold 20 Test Metrics (LightGBM, GPU, 5-subject CV)

Per-class metrics:
label	precision	recall		f1-score	support
0	0.7015		0.9540		0.8085		39857
1	0.0979		0.0062		0.0116		16199
2	0.1671		0.4918		0.2494		429

Global metrics:
Accuracy          : 0.6786
Balanced Accuracy : 0.4840
Micro-F1          : 0.6786
Macro-F1          : 0.3565
Weighted-F1       : 0.5757

Confusion matrix (rows = true, cols = predicted):
[[38022   921   914]
 [15961   100   138]
 [  218     0   211]]

Per-class confusion details (TP, FP, FN, TN):
Label 0: TP=38022, FP=16179, FN=1835, TN=449
Label 1: TP=100, FP=921, FN=16099, TN=39365
Label 2: TP=211, FP=1052, FN=218, TN=55004

################################################################################
OUTER Fold 21/23 (5-subject grouped CV)
################################################################################
Train subjects: 108
Test subjects : 5
[WARN] SM

c:\Users\LENOVO\Downloads\sp-data pre\xgb_gpu_env\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(


Saved model: C:\Users\LENOVO\Downloads\sp-data pre\LightGBM\output\lgbm_outer_21_5subj.pkl

OUTER Fold 21 Test Metrics (LightGBM, GPU, 5-subject CV)

Per-class metrics:
label	precision	recall		f1-score	support
0	0.8575		0.9710		0.9107		82501
1	0.3348		0.0507		0.0880		13238
2	0.1784		0.2216		0.1977		1313

Global metrics:
Accuracy          : 0.8353
Balanced Accuracy : 0.4144
Micro-F1          : 0.8353
Macro-F1          : 0.3988
Weighted-F1       : 0.7889

Confusion matrix (rows = true, cols = predicted):
[[80107  1315  1079]
 [12306   671   261]
 [ 1004    18   291]]

Per-class confusion details (TP, FP, FN, TN):
Label 0: TP=80107, FP=13310, FN=2394, TN=1241
Label 1: TP=671, FP=1333, FN=12567, TN=82481
Label 2: TP=291, FP=1340, FN=1022, TN=94399

################################################################################
OUTER Fold 22/23 (5-subject grouped CV)
################################################################################
Train subjects: 108
Test subjects : 5
[WARN

c:\Users\LENOVO\Downloads\sp-data pre\xgb_gpu_env\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(


Saved model: C:\Users\LENOVO\Downloads\sp-data pre\LightGBM\output\lgbm_outer_22_5subj.pkl

OUTER Fold 22 Test Metrics (LightGBM, GPU, 5-subject CV)

Per-class metrics:
label	precision	recall		f1-score	support
0	0.7600		0.9545		0.8462		54218
1	0.0810		0.0037		0.0070		16097
2	0.1239		0.3213		0.1788		940

Global metrics:
Accuracy          : 0.7313
Balanced Accuracy : 0.4265
Micro-F1          : 0.7313
Macro-F1          : 0.3440
Weighted-F1       : 0.6478

Confusion matrix (rows = true, cols = predicted):
[[51750   665  1803]
 [15705    59   333]
 [  634     4   302]]

Per-class confusion details (TP, FP, FN, TN):
Label 0: TP=51750, FP=16339, FN=2468, TN=698
Label 1: TP=59, FP=669, FN=16038, TN=54489
Label 2: TP=302, FP=2136, FN=638, TN=68179

################################################################################
OUTER Fold 23/23 (5-subject grouped CV)
################################################################################
Train subjects: 110
Test subjects : 3
[WARN] SMO

c:\Users\LENOVO\Downloads\sp-data pre\xgb_gpu_env\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(


Saved model: C:\Users\LENOVO\Downloads\sp-data pre\LightGBM\output\lgbm_outer_23_5subj.pkl

OUTER Fold 23 Test Metrics (LightGBM, GPU, 5-subject CV)

Per-class metrics:
label	precision	recall		f1-score	support
0	0.6791		0.8363		0.7495		4312
1	0.6421		0.2177		0.3251		1879
2	0.4144		0.5560		0.4749		714

Global metrics:
Accuracy          : 0.6390
Balanced Accuracy : 0.5367
Micro-F1          : 0.6390
Macro-F1          : 0.5165
Weighted-F1       : 0.6056

Confusion matrix (rows = true, cols = predicted):
[[3606  217  489]
 [1398  409   72]
 [ 306   11  397]]

Per-class confusion details (TP, FP, FN, TN):
Label 0: TP=3606, FP=1704, FN=706, TN=889
Label 1: TP=409, FP=228, FN=1470, TN=4798
Label 2: TP=397, FP=561, FN=317, TN=5630

GLOBAL Metrics Across All 5-subject CV Folds (LightGBM, GPU)

Per-class metrics:
label	precision	recall		f1-score	support
0	0.8122		0.9384		0.8708		1312916
1	0.2034		0.0294		0.0514		289844
2	0.0964		0.3085		0.1468		19917

Global metrics:
Accuracy          : 0.7683
Ba

In [3]:
import os
from pathlib import Path

import numpy as np
import pandas as pd
import lightgbm as lgb
import joblib

from sklearn.metrics import (
    precision_recall_fscore_support,
    accuracy_score,
    balanced_accuracy_score,
    f1_score,
    confusion_matrix,
)
from sklearn.utils import shuffle

from imblearn.under_sampling import RandomUnderSampler
from imblearn.over_sampling import SMOTE


# ============================================================
# 0) Paths and basic settings
# ============================================================

DATA_PATH = Path(r"C:\Users\LENOVO\Downloads\DF_ALL_4MOD_TRIMMED.csv")
MODELS_DIR = Path(r"C:\Users\LENOVO\Downloads\sp-data pre\LightGBM_only_egg\output")

os.makedirs(MODELS_DIR, exist_ok=True)

SUBJECT_COL = "subject"
LABEL_COL   = "label"

RANDOM_STATE = 42
FOLD_SIZE_SUBJECTS = 5  # 5-subject grouped CV (same idea as RF)

np.random.seed(RANDOM_STATE)


# ============================================================
# 1) Metadata columns (NOT used as features)
# ============================================================

meta_cols = [
    "subject",
    "run",
    "window_idx",
    "label",
    "run_base",
    "ecg_start_time_sec",
    "t_start",
    "t_end",
    "win_idx",
    "Unnamed: 0",
    "timestamp_center",
]


# ============================================================
# 2) Helper functions
# ============================================================

def hybrid_resample_l012(
    X,
    y,
    majority_class=0,
    mid_class=1,
    minority_class=2,
    max_majority_ratio=2.0,
    random_state=42,
):
    """
    Hybrid sampling strategy for labels {0, 1, 2} using:
      - Random UNDER-sampling for class 0 (majority)
      - SMOTE over-sampling for class 1 (preictal) and class 2 (seizure)
    """
    rng = np.random.RandomState(random_state)
    X = np.asarray(X)
    y = np.asarray(y)

    idx_maj = np.where(y == majority_class)[0]
    idx_mid = np.where(y == mid_class)[0]
    idx_min = np.where(y == minority_class)[0]

    n_maj = len(idx_maj)
    n_mid = len(idx_mid)
    n_min = len(idx_min)

    if n_mid == 0 or n_min == 0:
        raise ValueError("Classes 1 and 2 must be present for hybrid_resample_l012.")

    # 1) target counts
    mid_oversample_factor = 1.5
    target_mid = max(n_mid, int(n_mid * mid_oversample_factor))

    minority_target_ratio = 0.7
    raw_target_min = int(target_mid * minority_target_ratio)
    max_minority_factor = 10.0
    max_min = int(n_min * max_minority_factor)
    target_min = max(n_min, min(raw_target_min, max_min))

    target_maj = min(n_maj, int(max_majority_ratio * target_mid))

    sampling_strategy_under = {
        majority_class: target_maj,
        mid_class: n_mid,
        minority_class: n_min,
    }

    rus = RandomUnderSampler(
        sampling_strategy=sampling_strategy_under,
        random_state=random_state,
    )
    X_under, y_under = rus.fit_resample(X, y)

    n_mid_under = np.sum(y_under == mid_class)
    n_min_under = np.sum(y_under == minority_class)

    sampling_strategy_smote = {
        mid_class: max(n_mid_under, target_mid),
        minority_class: max(n_min_under, target_min),
    }

    try:
        smote = SMOTE(
            sampling_strategy=sampling_strategy_smote,
            random_state=random_state,
            k_neighbors=1,
        )
        X_bal, y_bal = smote.fit_resample(X_under, y_under)
    except ValueError:
        print("[WARN] SMOTE failed, falling back to simple oversampling.")

        X_bal = X_under
        y_bal = y_under

        idx_maj_u = np.where(y_under == majority_class)[0]
        idx_mid_u = np.where(y_under == mid_class)[0]
        idx_min_u = np.where(y_under == minority_class)[0]

        n_mid_u = len(idx_mid_u)
        n_min_u = len(idx_min_u)

        if n_mid_u < target_mid:
            extra_mid = target_mid - n_mid_u
            extra_idx_mid = rng.choice(idx_mid_u, size=extra_mid, replace=True)
            X_bal = np.concatenate([X_bal, X_under[extra_idx_mid]], axis=0)
            y_bal = np.concatenate([y_bal, y_under[extra_idx_mid]], axis=0)

        if n_min_u < target_min:
            extra_min = target_min - n_min_u
            extra_idx_min = rng.choice(idx_min_u, size=extra_min, replace=True)
            X_bal = np.concatenate([X_bal, X_under[extra_idx_min]], axis=0)
            y_bal = np.concatenate([y_bal, y_under[extra_idx_min]], axis=0)

    idx_all = np.arange(len(y_bal))
    idx_all = shuffle(idx_all, random_state=random_state)

    X_res = X_bal[idx_all]
    y_res = y_bal[idx_all]

    return X_res, y_res


def build_lgbm(params, num_classes):
    """
    Create a LightGBM classifier (multiclass, GPU).
    """
    return lgb.LGBMClassifier(
        objective="multiclass",
        num_class=num_classes,
        n_estimators=params["n_estimators"],
        max_depth=params["max_depth"],
        num_leaves=params["num_leaves"],
        learning_rate=params["learning_rate"],
        subsample=params["subsample"],
        colsample_bytree=params["colsample_bytree"],
        random_state=RANDOM_STATE,
        n_jobs=-1,
        verbose=-1,
        device_type="gpu",
        tree_learner="data",
        gpu_platform_id=0,
        gpu_device_id=0,
        max_bin=255,
    )


def lgbm_fit_predict(X_train, y_train, X_test, params, num_classes):
    model = build_lgbm(params, num_classes)
    print("Device type:", model.get_params()["device_type"])
    model.fit(X_train, y_train)
    y_test_pred = model.predict(X_test)
    return model, y_test_pred


def evaluate_metrics(y_true, y_pred, label_set=None):
    if label_set is None:
        label_set = np.unique(y_true)

    prec, rec, f1, support = precision_recall_fscore_support(
        y_true, y_pred, labels=label_set, zero_division=0
    )

    cm = confusion_matrix(y_true, y_pred, labels=label_set)
    total = cm.sum()

    tp = []
    fp = []
    fn = []
    tn = []

    for i in range(len(label_set)):
        TP = cm[i, i]
        FP = cm[:, i].sum() - TP
        FN = cm[i, :].sum() - TP
        TN = total - (TP + FP + FN)
        tp.append(TP)
        fp.append(FP)
        fn.append(FN)
        tn.append(TN)

    metrics = {
        "labels": label_set,
        "precision_per_class": prec,
        "recall_per_class": rec,
        "f1_per_class": f1,
        "support_per_class": support,
        "tp_per_class": np.array(tp),
        "fp_per_class": np.array(fp),
        "fn_per_class": np.array(fn),
        "tn_per_class": np.array(tn),
        "accuracy": accuracy_score(y_true, y_pred),
        "balanced_accuracy": balanced_accuracy_score(y_true, y_pred),
        "micro_f1": f1_score(y_true, y_pred, average="micro"),
        "macro_f1": f1_score(y_true, y_pred, average="macro"),
        "weighted_f1": f1_score(y_true, y_pred, average="weighted"),
        "confusion_matrix": cm,
    }

    return metrics


def print_metrics(metrics, header=""):
    labels  = metrics["labels"]
    prec    = metrics["precision_per_class"]
    rec     = metrics["recall_per_class"]
    f1      = metrics["f1_per_class"]
    support = metrics["support_per_class"]
    cm      = metrics["confusion_matrix"]

    if header:
        print("\n" + "=" * 70)
        print(header)
        print("=" * 70)

    print("\nPer-class metrics:")
    print("label\tprecision\trecall\t\tf1-score\tsupport")
    for i, c in enumerate(labels):
        print(f"{c}\t{prec[i]:.4f}\t\t{rec[i]:.4f}\t\t{f1[i]:.4f}\t\t{support[i]}")

    print("\nGlobal metrics:")
    print(f"Accuracy          : {metrics['accuracy']:.4f}")
    print(f"Balanced Accuracy : {metrics['balanced_accuracy']:.4f}")
    print(f"Micro-F1          : {metrics['micro_f1']:.4f}")
    print(f"Macro-F1          : {metrics['macro_f1']:.4f}")
    print(f"Weighted-F1       : {metrics['weighted_f1']:.4f}")

    print("\nConfusion matrix (rows = true, cols = predicted):")
    print(cm)

    total = cm.sum()
    print("\nPer-class confusion details (TP, FP, FN, TN):")
    for idx, c in enumerate(labels):
        TP = cm[idx, idx]
        FP = cm[:, idx].sum() - TP
        FN = cm[idx, :].sum() - TP
        TN = total - (TP + FP + FN)
        print(f"Label {c}: TP={TP}, FP={FP}, FN={FN}, TN={TN}")


# ============================================================
# 3) Load data
# ============================================================

print("Loading fused dataset...")
df = pd.read_csv(DATA_PATH)

if SUBJECT_COL not in df.columns or LABEL_COL not in df.columns:
    raise ValueError("Check SUBJECT_COL and LABEL_COL names. They are not found in the dataframe.")

print(f"Data shape: {df.shape}")
print("\nLabel distribution:")
print(df[LABEL_COL].value_counts())
print("\nLabel proportions (%):")
print(df[LABEL_COL].value_counts(normalize=True) * 100)

print("\nMetadata columns dropped from training:")
print(meta_cols)

# === EEG-only feature columns (channel 1 & channel 2) ===
eeg_feature_cols = [
    "ch1_Delta Bandpower",
    "ch1_Theta Bandpower",
    "ch1_Alpha Bandpower",
    "ch1_Beta Bandpower",
    "ch1_Gamma Bandpower",
    "ch1_Relative Delta Bandpower",
    "ch1_Relative Theta Bandpower",
    "ch1_Relative Alpha Bandpower",
    "ch1_Relative Beta Bandpower",
    "ch1_Relative Gamma Bandpower",
    "ch1_Interquartile Range",
    "ch1_Median",
    "ch1_Entropy",
    "ch1_Skewness",
    "ch1_Kurtosis",
    "ch1_Line Length",
    "ch1_Hjorth Mobility",
    "ch1_Hjorth Complexity",
    "ch2_Delta Bandpower",
    "ch2_Theta Bandpower",
    "ch2_Alpha Bandpower",
    "ch2_Beta Bandpower",
    "ch2_Gamma Bandpower",
    "ch2_Relative Delta Bandpower",
    "ch2_Relative Theta Bandpower",
    "ch2_Relative Alpha Bandpower",
    "ch2_Relative Beta Bandpower",
    "ch2_Relative Gamma Bandpower",
    "ch2_Interquartile Range",
    "ch2_Median",
    "ch2_Entropy",
    "ch2_Skewness",
    "ch2_Kurtosis",
    "ch2_Line Length",
    "ch2_Hjorth Mobility",
    "ch2_Hjorth Complexity",
]

# Optional safety check: ensure all selected feature columns exist in the dataframe
missing_feats = [c for c in eeg_feature_cols if c not in df.columns]
if len(missing_feats) > 0:
    raise ValueError(f"The following EEG feature columns are missing from the dataframe: {missing_feats}")

feature_cols = eeg_feature_cols
print(f"\nNumber of feature columns used for training: {len(feature_cols)}")

X_all = df[feature_cols].astype("float32").values
y_all = df[LABEL_COL].values
subjects_all = df[SUBJECT_COL].values

label_set = np.unique(y_all)
print(f"Unique labels: {label_set}")


# ============================================================
# 4) FIXED hyperparameters for LightGBM (no nested tuning)
# ============================================================

FIXED_PARAMS = {
    "n_estimators": 400,
    "max_depth": 18,
    "num_leaves": 60,
    "learning_rate": 0.05,
    "subsample": 0.8,
    "colsample_bytree": 0.8,
}

print("\nUsing FIXED LightGBM hyperparameters:")
print(FIXED_PARAMS)


# ============================================================
# 5) 5-subject grouped CV (NO nested)
# ============================================================

unique_subjects = np.array(sorted(np.unique(subjects_all)))
outer_folds = [
    unique_subjects[i:i + FOLD_SIZE_SUBJECTS]
    for i in range(0, len(unique_subjects), FOLD_SIZE_SUBJECTS)
]

print(f"\nTotal subjects: {len(unique_subjects)}, "
      f"Number of folds (5-subject CV): {len(outer_folds)}")

all_test_y_true = []
all_test_y_pred = []
outer_macro_f1_list = []

for outer_idx, test_subj in enumerate(outer_folds, start=1):
    print("\n" + "#" * 80)
    print(f"OUTER Fold {outer_idx}/{len(outer_folds)} (5-subject grouped CV)")
    print("#" * 80)

    is_test = np.isin(subjects_all, test_subj)
    is_train = ~is_test

    X_train = X_all[is_train]
    y_train = y_all[is_train]
    X_test  = X_all[is_test]
    y_test  = y_all[is_test]

    print("Train subjects:", len(np.unique(subjects_all[is_train])))
    print("Test subjects :", len(np.unique(test_subj)))

    # Hybrid resampling on TRAIN only
    X_train_bal, y_train_bal = hybrid_resample_l012(
        X_train, y_train,
        majority_class=0,
        mid_class=1,
        minority_class=2,
        max_majority_ratio=2.0,
        random_state=RANDOM_STATE + outer_idx
    )

    model, y_pred = lgbm_fit_predict(
        X_train_bal, y_train_bal,
        X_test,
        FIXED_PARAMS,
        num_classes=len(label_set)
    )

    model_path = MODELS_DIR / f"lgbm_outer_{outer_idx:02d}_5subj.pkl"
    joblib.dump(model, model_path)
    print(f"Saved model: {model_path}")

    m = evaluate_metrics(y_test, y_pred, label_set)
    print_metrics(m, header=f"OUTER Fold {outer_idx} Test Metrics (LightGBM, GPU, 5-subject CV)")

    all_test_y_true.append(y_test)
    all_test_y_pred.append(y_pred)
    outer_macro_f1_list.append(m["macro_f1"])


# ============================================================
# 6) GLOBAL metrics
# ============================================================

all_test_y_true = np.concatenate(all_test_y_true)
all_test_y_pred = np.concatenate(all_test_y_pred)

global_m = evaluate_metrics(all_test_y_true, all_test_y_pred, label_set)
print_metrics(global_m, header="GLOBAL Metrics Across All 5-subject CV Folds (LightGBM, GPU)")


# ============================================================
# 7) FINAL deployment model (train on ALL subjects with FIXED_PARAMS)
# ============================================================

X_full_bal, y_full_bal = hybrid_resample_l012(
    X_all, y_all,
    majority_class=0,
    mid_class=1,
    minority_class=2,
    max_majority_ratio=2.0,
    random_state=RANDOM_STATE + 999
)

final_model = build_lgbm(FIXED_PARAMS, num_classes=len(label_set))
final_model.fit(X_full_bal, y_full_bal)

deployment_model_path = MODELS_DIR / "lgbm_final_deployment_5subj_gpu.pkl"
joblib.dump(final_model, deployment_model_path)

print("\nFinal LightGBM deployment model (GPU) trained on all subjects and saved to:")
print(deployment_model_path)
print("Use this model for real-time or external testing on new patients.")

Loading fused dataset...
Data shape: (1622677, 113)

Label distribution:
label
0    1312916
1     289844
2      19917
Name: count, dtype: int64

Label proportions (%):
label
0    80.910495
1    17.862088
2     1.227416
Name: proportion, dtype: float64

Metadata columns dropped from training:
['subject', 'run', 'window_idx', 'label', 'run_base', 'ecg_start_time_sec', 't_start', 't_end', 'win_idx', 'Unnamed: 0', 'timestamp_center']

Number of feature columns used for training: 36
Unique labels: [0 1 2]

Using FIXED LightGBM hyperparameters:
{'n_estimators': 400, 'max_depth': 18, 'num_leaves': 60, 'learning_rate': 0.05, 'subsample': 0.8, 'colsample_bytree': 0.8}

Total subjects: 113, Number of folds (5-subject CV): 23

################################################################################
OUTER Fold 1/23 (5-subject grouped CV)
################################################################################
Train subjects: 108
Test subjects : 5
Device type: gpu


c:\Users\LENOVO\Downloads\sp-data pre\xgb_gpu_env\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(


Saved model: C:\Users\LENOVO\Downloads\sp-data pre\LightGBM_only_egg\output\lgbm_outer_01_5subj.pkl

OUTER Fold 1 Test Metrics (LightGBM, GPU, 5-subject CV)

Per-class metrics:
label	precision	recall		f1-score	support
0	0.8373		0.9558		0.8926		64940
1	0.0756		0.0138		0.0233		11160
2	0.1203		0.1141		0.1171		1332

Global metrics:
Accuracy          : 0.8056
Balanced Accuracy : 0.3612
Micro-F1          : 0.8056
Macro-F1          : 0.3444
Weighted-F1       : 0.7540

Confusion matrix (rows = true, cols = predicted):
[[62070  1857  1013]
 [10907   154    99]
 [ 1153    27   152]]

Per-class confusion details (TP, FP, FN, TN):
Label 0: TP=62070, FP=12060, FN=2870, TN=432
Label 1: TP=154, FP=1884, FN=11006, TN=64388
Label 2: TP=152, FP=1112, FN=1180, TN=74988

################################################################################
OUTER Fold 2/23 (5-subject grouped CV)
################################################################################
Train subjects: 108
Test subjects : 5

c:\Users\LENOVO\Downloads\sp-data pre\xgb_gpu_env\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(


Saved model: C:\Users\LENOVO\Downloads\sp-data pre\LightGBM_only_egg\output\lgbm_outer_02_5subj.pkl

OUTER Fold 2 Test Metrics (LightGBM, GPU, 5-subject CV)

Per-class metrics:
label	precision	recall		f1-score	support
0	0.8438		0.9494		0.8935		17789
1	0.1136		0.0206		0.0349		3150
2	0.1073		0.3314		0.1621		169

Global metrics:
Accuracy          : 0.8058
Balanced Accuracy : 0.4338
Micro-F1          : 0.8058
Macro-F1          : 0.3635
Weighted-F1       : 0.7595

Confusion matrix (rows = true, cols = predicted):
[[16888   507   394]
 [ 3013    65    72]
 [  113     0    56]]

Per-class confusion details (TP, FP, FN, TN):
Label 0: TP=16888, FP=3126, FN=901, TN=193
Label 1: TP=65, FP=507, FN=3085, TN=17451
Label 2: TP=56, FP=466, FN=113, TN=20473

################################################################################
OUTER Fold 3/23 (5-subject grouped CV)
################################################################################
Train subjects: 108
Test subjects : 5
Device ty

c:\Users\LENOVO\Downloads\sp-data pre\xgb_gpu_env\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(


Saved model: C:\Users\LENOVO\Downloads\sp-data pre\LightGBM_only_egg\output\lgbm_outer_03_5subj.pkl

OUTER Fold 3 Test Metrics (LightGBM, GPU, 5-subject CV)

Per-class metrics:
label	precision	recall		f1-score	support
0	0.8654		0.9040		0.8843		59595
1	0.1403		0.0137		0.0249		8566
2	0.0457		0.4707		0.0833		546

Global metrics:
Accuracy          : 0.7895
Balanced Accuracy : 0.4628
Micro-F1          : 0.7895
Macro-F1          : 0.3308
Weighted-F1       : 0.7708

Confusion matrix (rows = true, cols = predicted):
[[53873   717  5005]
 [ 8090   117   359]
 [  289     0   257]]

Per-class confusion details (TP, FP, FN, TN):
Label 0: TP=53873, FP=8379, FN=5722, TN=733
Label 1: TP=117, FP=717, FN=8449, TN=59424
Label 2: TP=257, FP=5364, FN=289, TN=62797

################################################################################
OUTER Fold 4/23 (5-subject grouped CV)
################################################################################
Train subjects: 108
Test subjects : 5
Devic

c:\Users\LENOVO\Downloads\sp-data pre\xgb_gpu_env\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(


Saved model: C:\Users\LENOVO\Downloads\sp-data pre\LightGBM_only_egg\output\lgbm_outer_04_5subj.pkl

OUTER Fold 4 Test Metrics (LightGBM, GPU, 5-subject CV)

Per-class metrics:
label	precision	recall		f1-score	support
0	0.8211		0.9503		0.8810		14104
1	0.0532		0.0052		0.0094		2700
2	0.2936		0.4165		0.3444		521

Global metrics:
Accuracy          : 0.7870
Balanced Accuracy : 0.4573
Micro-F1          : 0.7870
Macro-F1          : 0.4116
Weighted-F1       : 0.7290

Confusion matrix (rows = true, cols = predicted):
[[13403   243   458]
 [ 2622    14    64]
 [  298     6   217]]

Per-class confusion details (TP, FP, FN, TN):
Label 0: TP=13403, FP=2920, FN=701, TN=301
Label 1: TP=14, FP=249, FN=2686, TN=14376
Label 2: TP=217, FP=522, FN=304, TN=16282

################################################################################
OUTER Fold 5/23 (5-subject grouped CV)
################################################################################
Train subjects: 108
Test subjects : 5
Device t

c:\Users\LENOVO\Downloads\sp-data pre\xgb_gpu_env\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(


Saved model: C:\Users\LENOVO\Downloads\sp-data pre\LightGBM_only_egg\output\lgbm_outer_05_5subj.pkl

OUTER Fold 5 Test Metrics (LightGBM, GPU, 5-subject CV)

Per-class metrics:
label	precision	recall		f1-score	support
0	0.8601		0.8837		0.8717		50698
1	0.0974		0.0205		0.0339		7650
2	0.0454		0.3423		0.0801		710

Global metrics:
Accuracy          : 0.7654
Balanced Accuracy : 0.4155
Micro-F1          : 0.7654
Macro-F1          : 0.3286
Weighted-F1       : 0.7537

Confusion matrix (rows = true, cols = predicted):
[[44802  1426  4470]
 [ 6850   157   643]
 [  438    29   243]]

Per-class confusion details (TP, FP, FN, TN):
Label 0: TP=44802, FP=7288, FN=5896, TN=1072
Label 1: TP=157, FP=1455, FN=7493, TN=49953
Label 2: TP=243, FP=5113, FN=467, TN=53235

################################################################################
OUTER Fold 6/23 (5-subject grouped CV)
################################################################################
Train subjects: 108
Test subjects : 5
Dev

c:\Users\LENOVO\Downloads\sp-data pre\xgb_gpu_env\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(


Saved model: C:\Users\LENOVO\Downloads\sp-data pre\LightGBM_only_egg\output\lgbm_outer_06_5subj.pkl

OUTER Fold 6 Test Metrics (LightGBM, GPU, 5-subject CV)

Per-class metrics:
label	precision	recall		f1-score	support
0	0.8615		0.8859		0.8735		59673
1	0.0939		0.0620		0.0747		9000
2	0.1109		0.3436		0.1677		652

Global metrics:
Accuracy          : 0.7738
Balanced Accuracy : 0.4305
Micro-F1          : 0.7738
Macro-F1          : 0.3720
Weighted-F1       : 0.7632

Confusion matrix (rows = true, cols = predicted):
[[52864  5377  1432]
 [ 8079   558   363]
 [  422     6   224]]

Per-class confusion details (TP, FP, FN, TN):
Label 0: TP=52864, FP=8501, FN=6809, TN=1151
Label 1: TP=558, FP=5383, FN=8442, TN=54942
Label 2: TP=224, FP=1795, FN=428, TN=66878

################################################################################
OUTER Fold 7/23 (5-subject grouped CV)
################################################################################
Train subjects: 108
Test subjects : 5
Dev

c:\Users\LENOVO\Downloads\sp-data pre\xgb_gpu_env\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(


Saved model: C:\Users\LENOVO\Downloads\sp-data pre\LightGBM_only_egg\output\lgbm_outer_07_5subj.pkl

OUTER Fold 7 Test Metrics (LightGBM, GPU, 5-subject CV)

Per-class metrics:
label	precision	recall		f1-score	support
0	0.7146		0.9149		0.8024		84385
1	0.2607		0.0694		0.1096		32864
2	0.1385		0.2363		0.1746		656

Global metrics:
Accuracy          : 0.6754
Balanced Accuracy : 0.4069
Micro-F1          : 0.6754
Macro-F1          : 0.3622
Weighted-F1       : 0.6058

Confusion matrix (rows = true, cols = predicted):
[[77202  6442   741]
 [30360  2281   223]
 [  474    27   155]]

Per-class confusion details (TP, FP, FN, TN):
Label 0: TP=77202, FP=30834, FN=7183, TN=2686
Label 1: TP=2281, FP=6469, FN=30583, TN=78572
Label 2: TP=155, FP=964, FN=501, TN=116285

################################################################################
OUTER Fold 8/23 (5-subject grouped CV)
################################################################################
Train subjects: 108
Test subjects : 5

c:\Users\LENOVO\Downloads\sp-data pre\xgb_gpu_env\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(


Saved model: C:\Users\LENOVO\Downloads\sp-data pre\LightGBM_only_egg\output\lgbm_outer_08_5subj.pkl

OUTER Fold 8 Test Metrics (LightGBM, GPU, 5-subject CV)

Per-class metrics:
label	precision	recall		f1-score	support
0	0.7845		0.9423		0.8562		71070
1	0.2952		0.0245		0.0452		18993
2	0.0448		0.3071		0.0782		534

Global metrics:
Accuracy          : 0.7461
Balanced Accuracy : 0.4246
Micro-F1          : 0.7461
Macro-F1          : 0.3265
Weighted-F1       : 0.6816

Confusion matrix (rows = true, cols = predicted):
[[66966  1105  2999]
 [18032   465   496]
 [  365     5   164]]

Per-class confusion details (TP, FP, FN, TN):
Label 0: TP=66966, FP=18397, FN=4104, TN=1130
Label 1: TP=465, FP=1110, FN=18528, TN=70494
Label 2: TP=164, FP=3495, FN=370, TN=86568

################################################################################
OUTER Fold 9/23 (5-subject grouped CV)
################################################################################
Train subjects: 108
Test subjects : 5


c:\Users\LENOVO\Downloads\sp-data pre\xgb_gpu_env\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(


Saved model: C:\Users\LENOVO\Downloads\sp-data pre\LightGBM_only_egg\output\lgbm_outer_09_5subj.pkl

OUTER Fold 9 Test Metrics (LightGBM, GPU, 5-subject CV)

Per-class metrics:
label	precision	recall		f1-score	support
0	0.8064		0.8565		0.8307		42237
1	0.1504		0.0269		0.0457		9879
2	0.0159		0.3151		0.0303		292

Global metrics:
Accuracy          : 0.6971
Balanced Accuracy : 0.3995
Micro-F1          : 0.6971
Macro-F1          : 0.3022
Weighted-F1       : 0.6783

Confusion matrix (rows = true, cols = predicted):
[[36178  1501  4558]
 [ 8486   266  1127]
 [  198     2    92]]

Per-class confusion details (TP, FP, FN, TN):
Label 0: TP=36178, FP=8684, FN=6059, TN=1487
Label 1: TP=266, FP=1503, FN=9613, TN=41026
Label 2: TP=92, FP=5685, FN=200, TN=46431

################################################################################
OUTER Fold 10/23 (5-subject grouped CV)
################################################################################
Train subjects: 108
Test subjects : 5
Dev

KeyboardInterrupt: 